importblock: resolve circular import issue
Fixes #147

importblock uses Pipeline, and the pipeline module defines:

  _block_types = {
    ...
    "ImportBlock": importblock.ImportBlock,

which gives the following error:

```
src/instructlab/sdg/__init__.py:29: in <module>
    from .importblock import ImportBlock
src/instructlab/sdg/importblock.py:6: in <module>
    from . import pipeline
src/instructlab/sdg/pipeline.py:102: in <module>
    "ImportBlock": importblock.ImportBlock,
E   AttributeError: partially initialized module 'src.instructlab.sdg.importblock' has no attribute 'ImportBlock' (most likely due to a circular import)
```

This fixes the issue, but it's not very satisfactory, so I've included
a FIXME.

Signed-off-by: Mark McLoughlin <markmc@redhat.com>